-include $(PWD)/rules_base

%.rpi-exe: $(OFILES)
	$(CXX) -o $(LDFLAGS) $@ $(OFILES) $(LIBS)

CFLAGS := -O3 -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -DUSE_SDL_AUDIO -DBUFFERED -D_NO_JACK_ -D_NDEBUG
#CFLAGS	:= -g -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__ -D_NO_JACK_
 

CXXFLAGS:= $(CFLAGS)

EXTENSION:= rpi-exe

LIBS	:= -lSDL -lSDL_mixer -lpthread  
